### ISSUE TITLE
Docs: instructions on running against a specific branch or local build

### ISSUE THREAD

**Issue by carver** [ogenev/portal-hive#22]
@ogenev How would I run portal-hive against a local build of trin? It would be useful to have a section about that in the docs here: https://github.com/carver/portal-hive/blob/main/docs/overview.md

In my particular case, I want to test my local changes in trin to see if #20 will start working.

**Comment by ogenev** [comment]
`Portal-hive` needs a docker image to spin a client. If you work locally on Trin, you can build the image locally with:

```sh
cd trin
docker build -t trin-dev .
```
Then change the client `Dockerfile` to source from the new image (replacing [this](https://github.com/ogenev/portal-hive/blob/dc30e8092990a3b0960280d63de6cfc9e98aa4cc/clients/trin/Dockerfile#L3) with your local docker image name: `FROM trin-dev`).

When you run hive, it will use your local docker image to spin the Trin client.
